version: '2'
services:
    listeperenoel-app:
        image: listeperenoel
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://listeperenoel-mysql:3306/listeperenoel?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    listeperenoel-mysql:
        extends:
            file: mysql.yml
            service: listeperenoel-mysql
